version: "3.3"

services:

  androiddev_blog:
  
    # We are specifying the Ghost Image to run
    image: ghost:5.26.3-alpine

    
    # map host port 9198 (external) to Ghost's default internal port 2368
    ports:
      - 9198:2368

    environment:
      # the url of your blog. 
      url: https://androiddev.blog                                            

    labels:
     # tells Traefik to detect this docker container
     - traefik.enable=true

     # tells Traefik to look and match the host name androiddev.blog
     - traefik.http.routers.androiddev_blog.rule=Host(`androiddev.blog`)

     # tells Traefik to use the 'websecure' http router entry point.
     - traefik.http.routers.androiddev_blog.entrypoints=websecure

     # tells Traefik what certificate resolver to use - 'myresolver'
     - traefik.http.routers.androiddev_blog.tls.certresolver=myresolver

    volumes:

      # maps Ghost's data directory to the hosts directory.
      - /home/deploy/ghost_data/androiddev_blog/data:/var/lib/ghost/content
 
    networks:
     - web


networks:
  web:
    external: true
